/// Pure-Dart review deck builder — no Flutter/sqflite imports, unit-testable.
///
/// Popup quizzes are ALWAYS filtered out here; this is the single choke point
/// keeping them out of spaced repetition. Questions from `course_exam.json`
/// never enter either (the deck is built exclusively from quizzes.json).
library;

import '../../core/models/quiz.dart';
import '../../core/services/srs_scheduler.dart';

/// Second-stage filter applied after lecture/course scope selection.
enum ReviewFilterMode { wholeExam, wrongOnly, starredOnly, starredOrWrong }

/// One deck entry. Carries its source lecture/quiz ids so cross-lecture decks
/// can fetch question images from the right shelf server and write SRS state
/// back to the right rows.
class ReviewQuestion {
  const ReviewQuestion({
    required this.question,
    required this.quizId,
    required this.lectureId,
    required this.courseId,
    this.srs,
    this.exportAllowed = false,
    this.isPersonalQuiz = false,
    this.quizQuestionDirection = 'rtl',
    this.quizExplanationDirection = 'rtl',
  });

  final QuizQuestion question;
  final String quizId;
  final String lectureId;
  final String courseId;

  /// Null = never rated in review ("never seen", immediately due).
  final SrsRow? srs;

  // Carried over from the parent Quiz so aggregate exports spanning several
  // lectures/quizzes can apply the same permission gate as a single-quiz
  // export without re-fetching each quiz.
  final bool exportAllowed;
  final bool isPersonalQuiz;

  // Quiz-level direction defaults ('ltr' | 'rtl') — combine with
  // question.questionDirectionOverride/explanationDirectionOverride the same
  // way Quiz.effectiveQuestionDirection/effectiveExplanationDirection do.
  // Kept as plain strings (not dart:ui TextDirection) so this file stays
  // free of any direct Flutter/platform-binding import.
  final String quizQuestionDirection;
  final String quizExplanationDirection;

  ReviewQuestion withSrs(SrsRow? row) => ReviewQuestion(
        question: question,
        quizId: quizId,
        lectureId: lectureId,
        courseId: courseId,
        srs: row,
        exportAllowed: exportAllowed,
        isPersonalQuiz: isPersonalQuiz,
        quizQuestionDirection: quizQuestionDirection,
        quizExplanationDirection: quizExplanationDirection,
      );
}

class ReviewDeck {
  const ReviewDeck({
    required this.due,
    required this.neverSeen,
    required this.notYetDue,
    required this.nextDueAt,
  });

  /// Tracked questions whose due_at has passed, most-overdue first.
  final List<ReviewQuestion> due;

  /// Questions with no SRS row yet — treated as immediately due.
  final List<ReviewQuestion> neverSeen;

  /// Tracked but scheduled in the future (only reviewed in practice mode).
  final List<ReviewQuestion> notYetDue;

  /// Earliest future due time among [notYetDue]; null if nothing is tracked
  /// ahead. Drives the "next review in X" label on the caught-up screen.
  final DateTime? nextDueAt;

  int get dueCount => due.length + neverSeen.length;
  int get totalQuestions => due.length + neverSeen.length + notYetDue.length;

  /// The ordered question list for a session. Practice mode appends the
  /// not-yet-due questions after the due ones.
  List<ReviewQuestion> sessionList({required bool practice}) =>
      practice ? [...due, ...neverSeen, ...notYetDue] : [...due, ...neverSeen];
}

/// Builds a deck from the selected lectures' quizzes and their SRS rows.
///
/// [quizzesByLecture]: lectureId -> that lecture's quizzes.json content.
/// [srsRows]: keyed `"{questionId}::{quizId}"` (see [SrsRow.key]).
/// Orphan SRS rows (question ids regenerated by a lecture re-import) simply
/// never match a live question and are ignored — the new ids come back as
/// never-seen. Accepted limitation; no pruning.
ReviewDeck buildReviewDeck({
  required Map<String, List<Quiz>> quizzesByLecture,
  required Map<String, SrsRow> srsRows,
  required DateTime now,
  ReviewFilterMode filterMode = ReviewFilterMode.wholeExam,
  Set<String> starredKeys = const {},
}) {
  final due = <ReviewQuestion>[];
  final neverSeen = <ReviewQuestion>[];
  final notYetDue = <ReviewQuestion>[];

  quizzesByLecture.forEach((lectureId, quizzes) {
    for (final quiz in quizzes) {
      if (quiz.isPopupQuiz) continue; // popups never enter review
      for (final question in quiz.questions) {
        final key = '${question.id}::${quiz.id}';
        final srs = srsRows[key];
        if (!_passesFilter(filterMode, srs, starredKeys.contains(key))) {
          continue;
        }

        final entry = ReviewQuestion(
          question: question,
          quizId: quiz.id,
          lectureId: lectureId,
          courseId: quiz.courseId,
          srs: srs,
          exportAllowed: quiz.exportAllowed,
          isPersonalQuiz: quiz.isPersonalQuiz,
          quizQuestionDirection: quiz.questionDirection,
          quizExplanationDirection: quiz.explanationDirection,
        );
        if (entry.srs == null) {
          neverSeen.add(entry);
        } else if (!entry.srs!.dueAt.isAfter(now)) {
          due.add(entry);
        } else {
          notYetDue.add(entry);
        }
      }
    }
  });

  due.sort((a, b) => a.srs!.dueAt.compareTo(b.srs!.dueAt));
  notYetDue.sort((a, b) => a.srs!.dueAt.compareTo(b.srs!.dueAt));

  return ReviewDeck(
    due: due,
    neverSeen: neverSeen,
    notYetDue: notYetDue,
    nextDueAt: notYetDue.isNotEmpty ? notYetDue.first.srs!.dueAt : null,
  );
}

bool _passesFilter(ReviewFilterMode mode, SrsRow? srs, bool isStarred) {
  switch (mode) {
    case ReviewFilterMode.wholeExam:
      return true;
    case ReviewFilterMode.wrongOnly:
      // A never-attempted question (srs == null) can't be "wrong" yet.
      return srs != null && srs.lastRating == ReviewRating.again.index;
    case ReviewFilterMode.starredOnly:
      return isStarred;
    case ReviewFilterMode.starredOrWrong:
      return isStarred ||
          (srs != null && srs.lastRating == ReviewRating.again.index);
  }
}
