// GENERATED by scripts/gen_version.py — do not edit by hand.
// Regenerate before every build (`python scripts/gen_version.py --root .`)
// so the running app always reports the exact git commit it was built from.

const String kAppVersion = '1.0.0';
const int kBuildNumber = 126;
const String kGitCommit = '9a57f83+dirty';
const String kGitBranch = 'master';
const String kBuildTimestamp = '2026-07-14T19:06:35+00:00';

/// Short display string, e.g. "1.0.0+49 (90d24c9)", or "...+dirty)" if the
/// working tree had uncommitted changes when this build was made.
const String kVersionDisplay = '$kAppVersion+$kBuildNumber ($kGitCommit)';
